### ISSUE TITLE
我只是发表下我的看法，我知道我不该这么提issue的

### ISSUE THREAD

**Issue by neciszhang** [ustbhuangyi/vue-analysis#10]
你好：
      我很尊重你开源了很多的作品，这几天发生了DD前负责人的事情。Vue权威指南刚出来的时候，我在前端的一个公共号买了这本书，因为喜欢Vue，希望可以对vue有新的见解，也是对Vue的喜欢。谁知道收了这本书，我看了大部分都是Vue官网的例子和API，索然无趣。。。。我回复了公共号的人，对我说  请不要侮辱我的团队的努力什么的，原话不记得了。那个时候如果书里有你们对vue的剖析之类的，应该会很满意这本书的。只是发个唠叨。。。仅此而已==

**Comment by ustbhuangyi** [comment]
不好意思，那本书是有诸多问题，给你带来了不舒服，我表示抱歉。我和你说的那个负责人闹掰了，可能原因你也知道了。对我来说，做开源，做知识付费，都是想真正的去输出一些干货，有价值的内容，无论是帮助大家提升研发效率，还是教会大家一些技能知识，都是让我觉得无比有成就感的事情，希望能一直做下去。

**Comment by neciszhang** [comment]
@ustbhuangyi 感谢！坚持也是程序员的最大的素养
