### ISSUE TITLE
关于给数据添加__ob__属性的疑惑

### ISSUE THREAD

**Issue by mcfly001** [ustbhuangyi/vue-analysis#37]
- 你好，最近在研究vue源码过程中看了你的电子书，有个疑惑请教一下
源码
![image](https://user-images.githubusercontent.com/15622880/51298668-5d89b800-1a60-11e9-85ab-09d17147f444.png)

执行上述红框代码前的value
![image](https://user-images.githubusercontent.com/15622880/51298749-b8231400-1a60-11e9-92bf-8d796d630f66.png)
执行上述红框代码后的value
![image](https://user-images.githubusercontent.com/15622880/51298782-e99bdf80-1a60-11e9-8e1a-a66dccf45a22.png)

这里的__ob__好像是无穷无尽循环下去了，请问这样不会有问题么？

**Comment by ustbhuangyi** [comment]
JS 对象的循环引用是很正常的行为，除了不能被 JSON.stringify 之外，好像没啥问题。

**Comment by mcfly001** [comment]
谢谢解惑

> JS 对象的循环引用是很正常的行为，除了不能被 JSON.stringify 之外，好像没啥问题。
谢谢解惑
