### ISSUE TITLE
关于 vm.$vnode 书中的说法似乎有误。

### ISSUE THREAD

**Issue by njleonzhang** [ustbhuangyi/vue-analysis#4]
```
  // manually mounted instance, call mounted on self
  // mounted is called for render-created child components in its inserted hook
  if (vm.$vnode == null) {
    vm._isMounted = true
    callHook(vm, 'mounted')
  }

 这里注意 vm.$vnode 表示 Vue 实例的父虚拟 Node，所以它为 Null 则表示当前是根 Vue 的实例。
```
vm.$vnode 应该就是自己的vnode吧，mount的时候第一次调用 `updateComponent `，此时 $vnode 是 null，要触发一下 mounted hook 的回调 。如果是数据变化导致的 `mountComponent `，则$vnode 就不是 null 了，而是上一次render 的 vnode. 
不知道我理解的对不对。

**Comment by ustbhuangyi** [comment]
你理解的不对呀，`vm.$vnode` 就是父占位节点的 VNode，它是一个组件 VNode。数据变化会执行 `updateComponent ` 但是执行不到 `mountComponent` 这个逻辑

**Comment by njleonzhang** [comment]
不好意思 数据变化执行 mountComponent 是笔误，我已经改正。

**Comment by njleonzhang** [comment]
```
  const prevVnode = vm._vnode
  const prevActiveInstance = activeInstance
  activeInstance = vm
  vm._vnode = vnode
  // Vue.prototype.__patch__ is injected in entry points
  // based on the rendering backend used.
  if (!prevVnode) {
    // initial render
    vm.$el = vm.__patch__(vm.$el, vnode, hydrating, false /* removeOnly */)
  } else {
    // updates
    vm.$el = vm.__patch__(prevVnode, vnode)
  }
```

**Comment by ustbhuangyi** [comment]
Vue 是支持多例的。比如 cube-ui 的 [createAPI](https://didi.github.io/cube-ui/#/zh-CN/docs/create-api) 模块就是动态实例化一个 Vue 实例。

**Comment by EricTiger** [comment]
> Vue 是支持多例的。比如 cube-ui 的 [createAPI](https://didi.github.io/cube-ui/#/zh-CN/docs/create-api) 模块就是动态实例化一个 Vue 实例。

是否可以这么理解，因为vue是多实例的，所以每个component自身都会生成一个新的实例。而此处是为了阻止非compoent（div这种的）的mount是触发mounted的hook
