### ISSUE TITLE
数据驱动—vue实例挂载的实现，一节的疑问

### ISSUE THREAD

**Issue by buyixiaojiang** [ustbhuangyi/vue-analysis#47]
以下是原文

> 从上面的代码可以看到，mountComponent 核心就是先调用 vm._render 方法先生成虚拟 Node，再实例化一个渲染Watcher，在它的回调函数中会调用 updateComponent 方法，最终调用 vm._update 更新 DOM。

我的疑问是vm._render方法是在updateComponent里面执行的吧，怎么会发生在实例化渲染watcher之前呢？

**Comment by ustbhuangyi** [comment]
嗯，这里表述有误，应该是先实例化渲染 Watcher，然后执行 updateComponent 方法，接着执行 vm._render 方法生成虚拟 Node，最后执行 vm._update 更新 DOM
